version: "3.7"
services:
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_USER: pact
      POSTGRES_PASSWORD: pact
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  pact-broker:
    image: pactfoundation/pact-broker:2.55.0.0
    environment:
      PACT_BROKER_DATABASE_USERNAME: pact
      PACT_BROKER_DATABASE_PASSWORD: pact
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: pact
    ports:
      - 9292:9292
 